[options]
admin_passwd = admin
db_host = db_client01
db_port = 5432
db_user = odoo
db_password = odoo01
db_name = odoo_db01
proxy_mode = True
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/etc/odoo/extra-addons/dms,/etc/odoo/extra-addons/web,/etc/odoo/extra-addons/server-tools,/etc/odoo/extra-addons/server-ux
