events {
    worker_connections 1024;
}

http {
    upstream odoo_client01 {
        server odoo_client01:8069;
    }

    upstream odoo_client02 {
        server odoo_client02:8069;
    }

    upstream odoo_client01_poll {
        server odoo_client01:8072;
    }

    upstream odoo_client02_poll {
        server odoo_client02:8072;
    }

    server {
        listen 80;
        server_name client01.klynx.net;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name client01.klynx.net;

        ssl_certificate /etc/nginx/ssl/client01.crt;
        ssl_certificate_key /etc/nginx/ssl/client01.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        proxy_read_timeout 720s;
        proxy_connect_timeout 720s;
        proxy_send_timeout 720s;
        client_max_body_size 500M;

        location / {
    proxy_pass http://odoo_client01;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_redirect off;
    
    # Add Cloudflare real IP
    proxy_set_header CF-Connecting-IP $http_cf_connecting_ip;
}

        location /longpolling {
            proxy_pass http://odoo_client01_poll;
        }
    }

    server {
        listen 80;
        server_name client02.klynx.net;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name client02.klynx.net;

        ssl_certificate /etc/nginx/ssl/client02.crt;
        ssl_certificate_key /etc/nginx/ssl/client02.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        proxy_read_timeout 720s;
        proxy_connect_timeout 720s;
        proxy_send_timeout 720s;
        client_max_body_size 500M;

        location / {
            proxy_pass http://odoo_client02;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_redirect off;
        }

        location /longpolling {
            proxy_pass http://odoo_client02_poll;
        }
    }
}
