[options]

admin_passwd = odoo123
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo123
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/var/lib/odoo/addons/18.0
xmlrpc_port = 8069
logfile = /home/longo/odoo-docker/odoo.log
