[options]
admin_passwd = your_master_password
db_host = db_client01
db_port = 5432
db_user = odoo
db_password = odoo01
addons_path = /usr/lib/python3/dist-packages/odoo/addons
logfile = /var/log/odoo/odoo.log
